
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJvb3RAc2lzdGVtYS5jb20iLCJfaWQiOiI1ZGNkYWNhY2QyMzJjZjBhZGNiMGUxYzQiLCJuYW1lIjoicm9vdCIsImlhdCI6MTU3Mzc2MTk3NiwiZXhwIjoxNTczODQ4Mzc2fQ.Q3Sgbq40YR4sKbYyGno4vNtCqFxeyTJ7oWcoTx4HT9Y
@url = http://localhost:8357/api

// todas as rotas devem conter o campo token no header

###
# Login User
POST {{url}}/login
Content-Type: application/json

{
  "email": "root@sistema.com",
  "password": "123"
}

###
# Validação de token
GET {{url}}/me?token={{token}}
Content-Type: application/json

###
# Busca detalhes de um usuario
@id = 5dcdacacd232cf0adcb0e1c4
GET {{url}}/v1/users/{{id}}
Content-Type: application/json
authorization: {{token}}

###
# Busca todos os usuário paginados de 5 em 5
get {{url}}/v1/users/list?skip=0&limit=5
Content-Type: application/json
authorization: {{token}}

###
# Busca todos os usuário  com filtragem
get {{url}}/v1/users/filter?name=user1&date=2019-11-14
Content-Type: application/json
authorization: {{token}}

###
# Cria um usuário
POST {{url}}/v1/users
Content-Type: application/json
authorization: {{token}}

{
  "email": "teste@gmail.com",
  "password": "123",
  "name": "Teste user 2",
  "contatos": [
    {
      "type": "telefone",
      "value": "42999981464"
    },
    {
      "type": "celular",
      "value": "42999981464"
    },
    {
      "type": "email",
      "value": "thiago testes"
    },{
      "type": "linkedin",
      "value": "thiagohagy"
    }
  ]
}

###
# Edita um usuário
PATCH  {{url}}/v1/users/5dc86cf6b5798135d1dc429d
Content-Type: application/json
authorization: {{token}}

{
  "email": "thiago@gmasdil.com",
  "name": "thiago",
  "contatos": [{
      "type": "email0",
      "value": "thiagotestes.combr"
    }, {
      "type": "celular",
      "value": "42999981464"
    }, {
      "type": "email",
      "value": "thiago testes"
    }, {
      "type": "linkedin",
      "value": "thiagohagy"
    }
  ]
}

###
# Soft delete de um usuário
DELETE {{url}}/v1/users/5dc868c1f408113127aa0e28
Content-Type: application/json
authorization: {{token}}
